### ISSUE TITLE
Update GitHub Actions workflow to use Xcode 13.3

### ISSUE THREAD

**Issue by dmytro-anokhin** [bloomberg/xcdiff#103]
**Is your feature request related to a problem? Please describe.**
Currently the project uses Xcode 12.5.1. To keep it up to date we should update it to the latest version of Xcode.

**Describe the solution you'd like**
Update GitHub Actions to use Xcode 13.3 and macOS 12 (as it is required by Xcode 13.3).

**Comment by marciniwanicki** [comment]
Resolved https://github.com/bloomberg/xcdiff/pull/104
