### ISSUE TITLE
Question on CopyFilesComparator

### ISSUE THREAD

**Issue by michaelmcguire** [bloomberg/xcdiff#111]
I'm using [`CopyFilesComparator`](https://github.com/bloomberg/xcdiff/blob/main/Sources/XCDiffCore/Comparator/BuildPhasesComparator.swift#L20) as a base while working on #110 and was confused by quite a few the unit tests. As an example, the test [`testCompare_whenCopyFilesBuildPhaseOnlyInFirst_noDifference`](https://github.com/bloomberg/xcdiff/blob/d03725a4180f78782cbbdad491fb83afe49df8bb/Tests/XCDiffCoreTests/Comparator/CopyFilesComparatorTests.swift#L52):

```
    func testCompare_whenCopyFilesBuildPhaseOnlyInFirst_noDifference() throws {
        // Given
        let first = project()
            .addTarget(name: "Target1", productType: .application) { target in
                target.addBuildPhase(.copyFiles(.frameworks)) { _ in }
            }
            .projectDescriptor()
        let second = project()
            .addTarget(name: "Target1", productType: .application) { _ in }
            .projectDescriptor()

        // When
        let actual = try subject.compare(first, second, parameters: .all)

        // Then
        XCTAssertEqual(actual, [.init(tag: "copy_files", context: ["\"Target1\" target"])])
    }
```

(Note: there are many like this where no difference is expected even though the copy files phases are different)

Why would a project that has the copy files build phase not fail if the second one did not? Is it because you assume the `BuildPhaseComparator` will pick up the differences? Should I be doing the same for the enhancement to Run / Shell scripts comparisons?

**Comment by kwridan** [comment]
Hi @michaelmcguire 

I believe this is due to the comparator only showing differences in common copy files build phases while leaning on the generic `build_phases` comparator to flag any missing / additional build phases.

For example:

| Project 1 | Project 2 |
| --------- | -------- |
| ![project1](https://user-images.githubusercontent.com/11914919/187382880-27567faf-2999-48b5-aef3-6a5a49558673.png) | ![project2](https://user-images.githubusercontent.com/11914919/187382915-311207a1-8890-488a-aceb-24391efa3bf5.png) |


```
$ xcdiff -v -g "build_phases, copy_files"
❌ BUILD_PHASES > "Project" target

⚠️  Only in second (1):

  • CopyFiles


✅ COPY_FILES > "Project" target > Embed Frameworks
```

**Comment by michaelmcguire** [comment]
> I believe this is due to the comparator only showing differences in common copy files build phases while leaning on the generic `build_phases` comparator to flag any missing / additional build phases.

@kwridan Thanks for verifying!

Do you think it would be ok to perform more verification on position in the new `scripts` tag? The identity of a Run Script phase is highly dependent on where it's located within the list and it is a very common phase to run more than once (unlike most of the other build phases that can appear no more than once).

**Comment by kwridan** [comment]
> Do you think it would be ok to perform more verification on position in the new scripts tag? The identity of a Run Script phase is highly dependent on where it's located within the list and it is a very common phase to run more than once (unlike most of the other build phases that can appear no more than once).

Sure that makes sense, is the ordering not covered with `build_phases` comparator already or are there some cases that were missed?

| Project 1 | Project 2 |
| -------- | --------- |
| ![project1-phases](https://user-images.githubusercontent.com/11914919/187476852-92e6e2dc-510c-4570-9ca3-333d2c0ab963.png) | ![project2-phases](https://user-images.githubusercontent.com/11914919/187476869-5edcf72b-5b45-4366-9c74-78702b618412.png) |

e.g.

```sh
$  xcdiff -v -t "Project" -g "build_phases"

❌ BUILD_PHASES > "Project" target

⚠️  Value mismatch (1):

  • Different order
    ◦ Sources, Frameworks, Resources, ShellScript (runScript), Embed Frameworks (copyFiles)
    ◦ Sources, Frameworks, Resources, Embed Frameworks (copyFiles), ShellScript (runScript)
```

**Comment by michaelmcguire** [comment]
@kwridan I ended up implementing the new comparator in the same manner as the Copy Files and I think you're right, the ordering catches those differences. I'll have a PR open soon. Thanks for your continued help!
