### ISSUE TITLE
Remove SPMUtility dependency

### ISSUE THREAD

**Issue by tbrachkov** [bloomberg/xcdiff#26]
**Is your feature request related to a problem? Please describe.**
I appreciate the `SPMUtility` and the `ArgumentParser` does a great job, however if we remove the dependency of `SPMUtility` and use some other framework like: [kylef/Commander](https://github.com/kylef/Commander) we could then revise the closed issue: **Add podspec** #14.

**Describe the solution you'd like**
Remove the `SPMUtility` dependency from the `Package.swift` for both `XCDiffCore` and `XCDiffCommand`. In `XCDiffCore` we need to write an alternative implementaion for `line.spm_split(around: "=")`. It does not look like there are any other uses of the `SPMUtility` in the code.

**Describe alternatives you've considered**
We can use other dependency like: [Carthage/Commandant](https://github.com/Carthage/Commandant)
Instead of using a dependency to parse the command line arguments we can just implement our own module doing so as part of the tool.

**Additional context**
If we remove the `SPMUtility` then we can allow support for CocoaPods and Carthage.

**Comment by marciniwanicki** [comment]
Thanks @tbrachkov for opening the ticket. I like the suggestion! 

I believe removing `SPMUtility` from `XCDiffCore` would be a very nice win which does not require that much effort. It would also be fully transparent to the users.

It will allow to push `XCDiffCore` as a pod. `XCDiffCommand` is very shallow overlay which most of the libraries do not expose so I'd be OK if it's not available via CocoaPods at all (at least initially). 

On the other hand we really like the way `SPMUtility` allows to compose command parsers - we can use xcdiff as a standalone tool as well as a subcommand of a bigger command line project. I've never used https://github.com/kylef/Commander so I cannot tell if it offers similar feature.

PR for the `XCDiffCore` would be great! :) 🙌

**Comment by kwridan** [comment]
Resolved via #27
