### ISSUE TITLE
Replace the Swift Package Manager dependency with Swift Tools Support

### ISSUE THREAD

**Issue by kwridan** [bloomberg/xcdiff#46]
**Is your feature request related to a problem? Please describe.**

[Swift Package Manager](https://github.com/apple/swift-package-manager) is currently used as dependency to leverage some of the components and types within its utility libraries (e.g. `ArgumentParser` and `AbsolutePath`).

Recently those utility libraries have been extracted to their own package [Swift Tools Support](https://github.com/apple/swift-tools-support-core).

**Describe the solution you'd like**

To reduce the dependency footprint of xcdiff, we can replace the Swift PM dependency with SwiftToolSupport - as it only contains those utilities which xcdiff needs.

**Comment by marciniwanicki** [comment]
Resolved by https://github.com/bloomberg/xcdiff/pull/59
