### ISSUE TITLE
xcdiff --list could show which tags are enabled/disabled by default

### ISSUE THREAD

**Issue by natanrolnik** [bloomberg/xcdiff#49]
When I wanted to "filter" some tags while using xcdiff, I used `xcdiff --list` to print the tags. I removed 2 of them, and, to my surprise, diffing jumped from a few seconds to around 30.

I messaged @kwridan in the Tuist Slack, and he pointed me to this file: [Comparators.md](https://github.com/bloomberg/xcdiff/blob/master/Documentation/Comparators.md). Kas explained (as written in the mentioned md file) that the `RESOLVED_SETTINGS` tag depends on xcodebuild under the hood, and this is why this tag is disabled by default.

Ideally, listing the tags should inform the user which tags are enabled/disabled by default, so mimicking the default behavior is easier.

An example of this is the SwiftLint's rules command, which prints much more information:

<img width="1435" alt="SwiftLintRules" src="https://user-images.githubusercontent.com/1164565/79124199-7ccade80-7da4-11ea-8ddd-5ba0699caddc.png">

For xcdiff, a table with the tags, description, and enabled by default would be even better.

**Comment by marciniwanicki** [comment]
+1, that could be very useful :)
