### ISSUE TITLE
Print out usage description when no projects are detected

### ISSUE THREAD

**Issue by kwridan** [bloomberg/xcdiff#5]
**Is your feature request related to a problem? Please describe.**
When running `xcdiff` in a directory that doesn't contain two projects we currently print out an error. 

```
ERROR: Could not find 2 projects in the current directory
```

**Describe the solution you'd like**
We could display a more helpful error message such as:

```
Could not find 2 projects in the current directory, use `-p1` and `-p2` to specify the projects paths to compare
```

Alternatively, the usage instructions could be displayed.

**Comment by marciniwanicki** [comment]
Implemented by https://github.com/bloomberg/xcdiff/pull/11.
