### ISSUE TITLE
Lenient comparison between empty and nil arrays in build phases

### ISSUE THREAD

**Issue by natanrolnik** [bloomberg/xcdiff#50]
**Describe the bug**
When comparing build phases, I believe xcdiff could be more lenient when comparing the arrays of input files. For example, if one project's build phase has `nil` as **inputFileListPaths** or **outputFileListPaths**, and another project has an empty array, it triggers an error in the Build Phases section. Obviously, this is a diff, and if this is a bug or expected behavior is debatable. But in practical terms, they are identical.

**To Reproduce**
1. Create an Xcode project manually with no inputFileListPaths
2. Create another project generated by Tuist
3. xcdiff between the two
4. See the error below in the screenshot.

**Expected behavior**
A comparison between `nil` and empty array should not be considered an error.

**Screenshots**
<img width="664" alt="EmptyVsNilBuildPhaseInput" src="https://user-images.githubusercontent.com/1164565/79124489-14c8c800-7da5-11ea-9b4b-9ea174fad7f7.png">

**Environment (please complete the following information):**
 - macOS 10.15

**Comment by marciniwanicki** [comment]
Good catch! Many thanks for reporting it @natanrolnik.

**Comment by marciniwanicki** [comment]
Resolved by 95f413ac00fe399150be8fed72b86b2bf9e12923. Many thanks @natanrolnik!
