### ISSUE TITLE
Settings that appear in only one of the projects should inform their current value

### ISSUE THREAD

**Issue by natanrolnik** [bloomberg/xcdiff#51]
When working with Tuist and using xcdiff to get to the "ideal" Project.swift file, xcdiff is very valuable, especially in the Settings section. Not only xcdiff shows which values differ, but also which values are present **only** in one of them:

<img width="756" alt="XcdiffSettings" src="https://user-images.githubusercontent.com/1164565/79125320-aab12280-7da6-11ea-9b1a-2267662eb8b9.png">

It would be even better for the workflow, if xcdiff also printed the current value after the setting key. In the current workflow, I need to open such project, go to the right target, open the settings tab, look for the key, and then copy the value. Xcdiff has this data easily availble and could print it right away 😄

**Comment by marciniwanicki** [comment]
That's a very good idea! :)
