### ISSUE TITLE
Use swift-argument-parser

### ISSUE THREAD

**Issue by marciniwanicki** [bloomberg/xcdiff#94]
**Is your feature request related to a problem? Please describe.**
ArgumentParser API from swift-tools-support-core is deprecated and yields warnings when building with Xcode 13.

**Describe the solution you'd like**
We should switch to the more modern argument parser https://github.com/apple/swift-argument-parser.

**Comment by kwridan** [comment]
Was addressed via https://github.com/bloomberg/xcdiff/pull/105
